coverage:
  status:
    project:
      default:
        # Allow project coverage to decrease by 0.1%
        # We don't want to fail projects where minor changes
        # cause coverage to decrease slightly
        threshold: 0.1
